### ISSUE TITLE
Question about FID score

### ISSUE THREAD

**Issue by YouWillLikeIt** [jingyang2017/Face-and-Image-super-resolution#2]
Hi, Thanks very much for sharing your codes.
Here I have a question about the detail,
when you get fid-score, which dimensionality of Inception features do you use
Thanks

**Comment by jingyang2017** [comment]
CUDA_VISIBLE_DEVICES=0, python fid_score.py /Dataset/HIGH/SRtrainset_2/ test_res/
This code is from https://github.com/mseitzer/pytorch-fid
parser.add_argument('--dims', type=int, default=2048,
                    choices=list(InceptionV3.BLOCK_INDEX_BY_DIM),
                    help=('Dimensionality of Inception features to use. '
'By default, uses pool3 features'))
